config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: redirect('/users/sign_in')
  root 'events#index'
  # root 'devise/sessions#new'

  # devise_scope :user do
  #   get 'users/:id', to: 'devise/registrations#show', as: 'user'
  # end

  get 'users/:id', to: 'users#show', as: 'user'

  # add a new member route for events to handle the attendance section.
  resources :events do
    member do
      post 'attend'
    end
  end

  # set up standard routes for the event_attendees model
  resources :event_attendees
  # root 'devise/sessions#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :users
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id

  delegate :email, to: :creator, prefix: true

  scope :upcoming, -> { where 'event_date >= ?', Time.now }
  scope :past, -> { where 'event_date < ?', Time.now }

  # def self.past
  #   where('event_date < ?', Time.now)
  # end

  # def self.upcoming
  #   where('event_date >= ?', Time.now)
  # end

  # before_create :set_creator

  # private

  # def set_creator
  #   self.creator = current_user
  # end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  delegate :email, to: :attendee, prefix: true # enables the email field on the user object to be accessed via the attendee_email method

  delegate :event_title, to: :attended_event, prefix: true
  delegate :event_date, to: :attended_event, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendees, foreign_key: 'attendee_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def index
    # @user = current_user
    # @created_events = @user.created_events
    @event_attendees = EventAttendee.all
  end

  def show
    @event_attendee = EventAttendee.find(params[:id])
  end

  def new
    @event_attendee = EventAttendee.new
  end

  def create
    @event_attendee = EventAttendee.new(event_attendee_params)
    # @event = current_user.created_events.build(event_params)
    if @event_attendee.save
      redirect_to @event_attendee
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event_attendee = EventAttendee.find(params[:id])
  end

  def update
    @event_attendee = EventAttendee.find(params[:id])
    if @event_attendee.update(eventattendee_params)
      redirect_to @event_attendee
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event_attendee = EventAttendee.find(params[:id])
    @event_attendee.destroy
    redirect_to event_attendees_path
  end

  private

  def event_attendee_params
    params.require(:event_attendee).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @created_events = @user.created_events
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.event_attendees
  end

  def new
    @event = Event.new
  end

  def create
    # @event = Event.new(event_params)
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  # define a new action attend to handle the request when a user clicks on the "attend" button

  def attend
    @event = Event.find(params[:id])
    @event_attendee = EventAttendee.new(attendee_id: current_user.id, attended_event_id: @event.id) # this creates a new EventAttendee record with the @event.id and the current_user.id as input parameters

    if @event_attendee.save
      redirect_to @event, notice: 'You have now attendeding this event.'
    else
      redirect_to @event, alert: 'There was an error. Please try again.'
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_title, :event_date, :description, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Controller to for users to sign up for the application

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    # @user = User.find(params[:id])
    return if current_user.nil?

    @user = current_user
    @created_events = @user.created_events
    @attended_events = @user.event_attendees

    event_ids = @user.event_attendees.pluck(:attended_event_id) # this retrieves an array of event_ids from the attended_event table

    # both of these variables are used to display the past and future events that the user has attended. The records come from the events table, NOT the event_attendees table
    @past_attended_events = Event.where(id: event_ids).where('events.event_date < ?', Time.now) # the event_ids array is used to retrieve only the attended events from the events table, it is then filtered to only retrieve events that have a date less than the current time
    @future_attended_events = Event.where(id: event_ids).where('events.event_date >= ?', Time.now) # the event_ids array is used to retrieve only the attended events from the events table, it is then filtered to only retrieve events that have a date greater than or equal to the current time
  end

  # def show
  #   return if current_user.nil?

  #   @user = current_user
  #   @created_events = @user.created_events
  #   event_ids = @user.event_attendees.pluck(:event_id)
  #   @past_attended_events = Event.where(id: event_ids).where('events.event_date < ?', Time.now)
  #   @future_attended_events = Event.where(id: event_ids).where('events.event_date >= ?', Time.now)
  # end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User was successfully created.'
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendees/_form.html.erb
<%= form_with model: event_attendee do |form| %>
  <div>
    <%= form.label :attended_event_id %><br>
    <%= form.text_field :attended_event_id %>
    <% event_attendee.errors.full_messages_for(:attended_event_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :attendee_id %><br>
    <%= form.text_area :attendee_id %><br>
    <% event_attendee.errors.full_messages_for(:attendee_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/event_attendees/edit.html.erb
<h1>Edit event_attendee record</h1>
<%= render 'form', event_attendee: @event_attendee %>

app/views/event_attendees/index.html.erb
<!--
<h1>Events</h1>
<% if @events.nil? %>
  <p>No events found.</p>
<% else %>
  <ul>
    <% @events.each do |event| %>
      <li>
        <%= link_to event.event_title, event %> | <%= event.event_date%> | <%= event.creator_id%> | <%= event.creator_email%>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'New event', new_event_path %>
<div>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>.
    <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
      <%= submit_tag "Log out" %>
    <% end %>
  <% else %>
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>
<div>
  <%= link_to 'Edit User details', edit_user_registration_path%>
</div>
-->
<% if user_signed_in? %>
  <h2>Event Attendee records</h2>
  <% if @event_attendees.nil? %>
    <p>No events found.</p>
  <% else %>
    <ul>
      <% @event_attendees.each do |event_attendee| %>
        <li><%= link_to event_attendee.attendee_id, event_attendee %> | <%= event_attendee.attended_event_id%></li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <p>No user logged in.</p>
<% end %>
<%= link_to 'New event attendee record', new_event_attendee_path %>
<div>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>.
    <!--
    <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } %>
    -->
    <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
      <%= submit_tag "Log out" %>
    <% end %>
  <% else %>
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>
<div>
  <%= link_to 'Edit User details', edit_user_registration_path%>
</div>

app/views/event_attendees/new.html.erb
<h1>Create new event attendee record</h1>
<%= render 'form', event_attendee: @event_attendee %>

app/views/event_attendees/show.html.erb
<h1>Event Attendee record detail</h1>
<ul>
  <li><%=  @event_attendee.attended_event_id %> | <%= @event_attendee.attendee_id%> </li>
</ul>
<%= link_to 'Edit event attendee record', edit_event_attendee_path %>
<%= link_to "Delete event", event_attendee_path(@event_attendee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
<div>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>.
    <!--
    <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } %>
    -->
    <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
      <%= submit_tag "Log out" %>
    <% end %>
  <% else %>
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>
<div>
  <%= link_to 'Edit User details', edit_user_registration_path%>
</div>

app/views/events/index.html.erb
<!--
<div class="container">
  <div class="header">
    <h1>Events</h1>
    <% if user_signed_in? %>
      <div class="user-details">
        <div class="user-email"><%= link_to current_user.email, edit_user_registration_path, class: 'user-email-link'%></div>
        <div class="log-in">
          <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
            <%= submit_tag "Log out", class: "log-out-button"%>
          <% end %>
        </div>
      <% else %>
        <div class="log-out">
          <%= link_to "Log in", new_user_session_path %>
        </div >
      <% end %>
    </div>
  </div>
</div> -->
<div class="main">
  <h2>Upcoming Events</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Description</th>
        <th>Location</th>
        <th>Creator Email</th>
        <!-- Add more columns as needed -->
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @upcoming_events.each do |event| %>
        <tr>
          <td><%= link_to event.event_title, event %></td>
          <td><%= event.event_date.strftime("%d %B %Y") %></td>
          <td><%= event.description %></td>
          <td><%= event.location %></td>
          <td><%= event.creator_email%></td>
          <!-- Add more columns as needed -->
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h2>Past Events</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Description</th>
        <th>Location</th>
        <th>Creator Email</th>
        <!-- Add more columns as needed -->
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @past_events.each do |event| %>
        <tr>
          <td><%= link_to event.event_title, event %></td>
          <td><%= event.event_date.strftime("%d %B %Y") %></td>
          <td><%= event.description %></td>
          <td><%= event.location %></td>
          <td><%= event.creator_email%></td>
          <!-- Add more columns as needed -->
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.event_title %></h1>
<ul>
  <li><%= @event.event_title %></li>
  <li><%= @event.event_date %></li>
  <li><%= @event.creator_id %></li>
  <li><%= @event.creator_email %></li>
  <ul>
    <%# The url: attend_event_path calls the the events#attend method with the input @event. %>
    <%= form_with url: attend_event_path(@event), method: :post, local: true do |form| %>
      <%= form.submit 'Attend', class: 'button' %>
    <% end %>
    <h2>Attendees:</h2>
    <ul>
      <% @attendees.each do |attendee| %>
        <li><%= attendee.attendee_id %> | <%= attendee.attendee_email %> </li>
      <% end %>
    </ul>
    <%= link_to 'Edit', edit_event_path(@event) %>
    <%= link_to 'All events', events_path%>
    <%= link_to "Delete event", event_path(@event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinPrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>
  <body>
    <div class="header">
      <h1><%= link_to "Events", root_path %></h1>
      <% if user_signed_in? %>
        <div class="user-details">
          <div class="user-email"><%= link_to current_user.email, edit_user_registration_path, class: 'user-email-link'%></div>
          <div class="log-in">
            <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
              <%= submit_tag "Log out", class: "log-out-button"%>
            <% end %>
          </div>
        <% else %>
          <div class="log-out">
            <%= link_to "Log in", new_user_session_path %>
          </div >
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %><br>
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if @users.nil? %>
  <p>No users found.</p>
<% else %>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.username, user %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <h1><%= @user.email %></h1>
  <h2>Events Created:</h2>
  <ul>
    <% @created_events.each do |event| %>
      <li><%= link_to event.event_title, event %> | <%= event.event_date%> | <%= event.creator_id%> | <%= event.creator_email%></li>
    <% end %>
  </ul>
<% else %>
  <p>No user logged in.</p>
<% end %>
<%= link_to 'New event', new_event_path %>
<h2>Attended Events</h2>
<ul>
  <% @attended_events.each do |event_attendee| %>
    <li><%= event_attendee.attended_event_id %> | <%= event_attendee.attended_event_event_title%> | <%= event_attendee.attended_event_event_date %></li>
  <% end %>
</ul>
<h2> Past events</h2>
<ul>
  <% @past_attended_events.each do |event| %>
    <li><%= event.id %> | <%= event.event_title%> | <%= event.event_date %></li>
  <% end %>
</ul>
<h2> Upcoming events</h2>
<ul>
  <% @future_attended_events.each do |event| %>
    <li><%= event.id %> | <%= event.event_title%> | <%= event.event_date %></li>
  <% end %>
</ul>
<div>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>.
    <!--
    <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } %>
    -->
    <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_method: "delete" } do %>
      <%= submit_tag "Log out" %>
    <% end %>
  <% else %>
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>
<div>
  <%= link_to 'Edit User details', edit_user_registration_path%>
</div>